# The URL the site will be built for
base_url = "https://www.nuclearcarrot.co.uk"

compile_sass = true
highlight_code = true
generate_rss = true
rss_limit = 2

theme="hyde"


[extra]
hyde_sticky = false

hyde_links = [
    {url = "/", name = "Blog"},
    {url = "/aboutme", name = "About Me"},
    {url = "/projects", name = "Projects"},
    {url = "/notes", name = "Notes"},
]
